defaults:
  - ../config/smart_score_math
  - _self_

# Override paths for testing
save_path: '/home/pramit/hrl-nips-work/hrl-reasoning/.test_models/smart_score'

# Minimal model settings for testing
max_new_tokens: 10
max_tokens: 10

# Minimal training settings for testing
rollout_size: 2
eval_size: 2
batch_size: 2
iterations: 2
epochs: 1
actor_epochs: 1
warmup_iter: 1
grad_accum_steps: 1
max_micro_batch_size: 2
gradient_accumulation_steps: 1
stage1_steps: 1
stage2_steps: 1

# Disable wandb for testing
use_wandb: false
run_name: 'test-smart-score' 